name = "sdn1palapa-web-cms"
compatibility_date = "2024-09-01"
pages_build_output_dir = "dist"

# Cloudflare KV Namespace configuration (Primary ID for web sekolah1)
# Note: Cloudflare requires unique ID per kv_namespaces block
[[kv_namespaces]]
binding = "SCHOOL_CMS_KV"
id = "5b4256f6-8ce8-4a13-ae5c-0ae37fcd9b9b"


